name: Update website

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIV_KEY }}
          script_stop: true
          script: |
            whoiam
            ls
            cd fediverso.gal
            ls
            git pull
            echo $PATH
            deno task lume